name: Pre-commit checks

on:
  push:
    branches: [ master, develop**, vb/precommit ]
    tags:
      - '*'
  pull_request:
    branches: [ master, develop** ]

jobs:

  build_and_test:
      runs-on: ubuntu-latest

      defaults:
        run:
          # Required when using an activated conda environment in steps
          # See https://github.com/conda-incubator/setup-miniconda#IMPORTANT
          shell: bash -l {0}

      steps:
        - uses: actions/checkout@v2

        - name: Set up conda
          uses: conda-incubator/setup-miniconda@v2
          with:
            auto-update-conda: true
            python-version: 3.9

        - name: Install pre-commit
          run: |
            conda install -c conda-forge pre-commit
            conda info
            conda list

        - name: Run pre-commit
          run: |
            pre-commit run --all-files
